version: '3'
services:
  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    hostname: kafka1
    user: 'root'
    networks:
      kafka_network:
        ipv4_address: 192.168.1.101
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://192.168.1.101:29092,CONTROLLER://192.168.1.101:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://192.168.1.101:29092,EXTERNAL://192.168.1.101:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@192.168.1.101:29093,2@192.168.1.102:29093,3@192.168.1.103:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/data/kafka1'
    volumes:
      - ./data/kafka1:/data/kafka1

  kafka2:
    image: confluentinc/cp-kafka
    container_name: kafka2
    hostname: kafka2
    user: 'root'
    networks:
      kafka_network:
        ipv4_address: 192.168.1.102
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://192.168.1.102:29092,CONTROLLER://192.168.1.102:29093,EXTERNAL://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://192.168.1.102:29092,EXTERNAL://192.168.1.102:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@192.168.1.101:29093,2@192.168.1.102:29093,3@192.168.1.103:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/data/kafka2'
    volumes:
      - ./data/kafka2:/data/kafka2

  kafka3:
    image: confluentinc/cp-kafka
    container_name: kafka3
    hostname: kafka3
    user: 'root'
    networks:
      kafka_network:
        ipv4_address: 192.168.1.103
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://192.168.1.103:29092,CONTROLLER://192.168.1.103:29093,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://192.168.1.103:29092,EXTERNAL://192.168.1.103:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@192.168.1.101:29093,2@192.168.1.102:29093,3@192.168.1.103:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/data/kafka3'
    volumes:
      - ./data/kafka3:/data/kafka3

  kafka-ui:
    image: "provectuslabs/kafka-ui:v0.7.1"
    container_name: kafka-ui
    networks:
      kafka_network:
        ipv4_address: 192.168.1.104
    ports:
      - "80:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=dobby-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.1.101:29092,192.168.1.102:29092,192.168.1.103:29092
    depends_on:
      - kafka1
      - kafka2
      - kafka3

networks:
  kafka_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
